blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^index', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/[#]?[0-9]?$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchiivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^search/$', views.search, name='search'),
    url(r'^img/(.+)$',views.genrate_qrcode, name='genrate_qrcode'),
    url(r'^train',views.train,name='train'),
    url(r'^test',views.test,name='test'),
    url(r'^ajax_info',views.ajax_info,name='ajax_info'),
    url(r'^getruning', views.getruning, name='getruning'),
]

blogproject/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from blog.feeds import AllPostsRssFeed
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^', include('weixin.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
#    url(r'^accounts/', include('users.urls')),
   #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}), 
   #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += staticfiles_urlpatterns()

comments/urls.py
# app_name = 'comments'
# urlpatterns = [
#     url(r'^comnent/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
# ]
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
import markdown
from django.utils.html import strip_tags
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

from  django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Post2(models.Model):
    body = RichTextUploadingField(verbose_name='正文')


@python_2_unicode_compatible
class Category(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    flag_name= ((1,'显示'),
               (2,'隐藏'),)
    title = models.CharField(u'标题',max_length=70)
    body = RichTextUploadingField(u'内容')
    created_time = models.DateTimeField(u'发表时间', editable = True)
    modified_time = models.DateTimeField(u'更新时间', null=True,auto_now=True)
    # 文章摘要
    excerpt = models.CharField(u'摘要',max_length=200, blank=True)
    # 文章分类标签
    category = models.ForeignKey('Category')
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者，这里从User 是从Django.contrib.auth.models 导入

    author = models.ForeignKey(User)
    views = models.PositiveIntegerField(default=0)
    flag = models.IntegerField('标记',choices=flag_name)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(
                extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                ]
            )
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models

from django.utils.six import python_2_unicode_compatible

# Create your models here.

# @python_2_unicode_compatible
# class Comment(models.Model):
#     name = models.CharField(max_length=100)
#     emile = models.EmailField(max_length=255)
#     url = models.URLField(blank=True)
#     text = models.TextField()
#     create_time = models.DateTimeField(auto_now_add=True)
#
#     post = models.ForeignKey('blog.Post')
#
#     def __str__(self):
#         return self.text[:20]

from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100,default='游客')
    email = models.EmailField(max_length=255,blank=True)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20],self.created_time

blog/views.py
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentForm
from django.http import HttpResponse
from .models import Post, Category, Tag
from .pagination import pagination
from django.db.models import Q
from django.views.decorators.cache import cache_page
import json
import time as time1
from weixin.get12306.get12306 import get_query_url, GetInfoTrain
from weixin.models import ParseStation,UserInfo,UserLocation
from django.contrib.auth.decorators import login_required



def test(request):
    return render(request, 'weixin/test.html', )

@login_required()
def getruning(request):
    """
    :param request:
    :return: 获取位置信息并返回
    """
    if request.method== "GET":
        userinfos = UserInfo.objects.filter().all()
        return render(request,"weixin/get_runing.html",{'userinfos':userinfos,})
    if request.method =="POST":
        userid = request.POST.get('id')
        localtion_list=[]
        user_localtions = UserLocation.objects.filter(user_id=userid).order_by('-createTime')[0:1000]
        for localtion in user_localtions:
            localtion_list.insert(0,[float(localtion.Longitude),float(localtion.Latitude)])
        localtion_list_dic = json.dumps({'localtion_data':localtion_list,})
        return HttpResponse(localtion_list_dic)



def ajax_info(request):
    if request.method == "POST":
        username = request.POST.get('username', '芜湖')
        print(username)
        return HttpResponse


train_station = ParseStation.objects.all()


def train(request):
    if request.method == 'GET':
        time = request.GET.get('time', time1.strftime('%Y-%m-%d', time1.localtime(time1.time())))
        place = request.GET.get('place', '上海')
        destination = request.GET.get('destination', '北京')
        dic = {'time': time, 'place': place, 'destination': destination}
        str = time + ' ' + place + ' ' + destination
        url = get_query_url(str)
        content = GetInfoTrain(url, True)
        return render(request, 'weixin/train.html',
                      {'train_station': train_station, 'content': content, "dic": json.dumps(dic)})
    if request.method == 'POST':
        time = request.POST.get('time')
        place = request.POST.get('place')
        destination = request.POST.get('destination')
        # print('时间:'+time)
        # print('出发地:'+place)
        # print('目的地:'+destination)
        str = time + ' ' + place + ' ' + destination
        url = get_query_url(str)
        content = GetInfoTrain(url, True)
        # dic = {'time': time, 'place': place, 'destination': destination}
        return HttpResponse(json.dumps(content))


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = "请输入关键词"
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q),flag=1)
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    # 记得在顶部导入 CommentForm
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all()
    URL = request.get_host() + request.path
    print(URL)
    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {'post': post,
               'form': form,
               'comment_list': comment_list,
               'URL': URL
               }
    return render(request, 'blog/detail.html', context=context)


@cache_page(60 * 15)
def archives(request, year, month):
    # print(year,month)
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month,
                                    flag=1).order_by('-created_time')
    # for post in post_list:
    #     print(post.title)

    return render(request, 'blog/index.html', context={'post_list': post_list})


class IndexView(pagination):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        return super(IndexView,self).get_queryset().filter(flag=1)

class ArchiivesView(pagination):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return super(ArchiivesView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'),
                                                                created_time__month=self.kwargs.get('month'),
                                                                flag=1)


class CategoryView(pagination):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(pagination):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def genrate_qrcode(request, data):
    import qrcode
    img = qrcode.make(data)
    from django.utils.six import BytesIO
    buf = BytesIO()
    img.save(buf)
    imge_stream = buf.getvalue()

    response = HttpResponse(imge_stream, content_type='image/png')
    return response

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="{% url 'blog:archives' post.created_time.date.year post.created_time.date.month %}"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#1">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body | safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3  name="1" id="1" >发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}

{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="{% url 'blog:archives' post.created_time.date.year post.created_time.date.month %}"><time class="entry-date"
                                                              datetime="{{ post.created_time }} ">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a
                            href="{{ post.get_absolute_url }}#1">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    {% if is_paginated %}
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    {% endif %}
{% endblock main %}